name: melanoma web application
on: push
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: prudhvi9999/melanoma
          tags: ${{ github.run_number }}, latest
    
  deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECTID }}
          SERVICE: melanoma-detection
          REGION: asia-south1
          # IMAGE_NAME: asia.gcr.io/$PROJECT_ID/$SERVICE
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            project_id: ${{ secrets.GCP_PROJECTID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}
            export_default_credentials: true

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}

        - name: Push Docker image
          run: docker push asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }}
        
        # - name: setting project id
        #   run: gcloud config set project experimental-285401
        #   #secrets not working in run command

        - name: Deploy Docker image
          run: gcloud run deploy $SERVICE --image asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{  github.sha }} --region $REGION --memory 2Gi --platform managed
          #service is the name of the app you want to deploy on
          #gcloud run deploy melanoma-detection --image IMAGE_URL